### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by pedromorgan** [piface/pifacecommon#17]
Is anyone actively maintainting the documentation ?

One problem I have is that pifacedigital docs don't line to pifacecommon docs etc.

Am familiar with sphinx so its easy to do, including branding the docs (logo) and sticking a navigation on top. (links to git, blog etc)

**Comment by pedromorgan** [comment]
Reviving this bug..

and working on a cunning (am farmers son from wales and know what a fox is like) plan to automate the whole docs, all in one go and interlinked on one website..

Atmo its a mish mash of stuff.. when it fact all that needs to happen is any code change fires of a compile.. but in out case.. all the docs need to be compiled..
eg a new "function" or class.. a change to a method signature.. interlinking together to a function that does not exist etc...

**Comment by tompreston** [comment]
Hey! So sorry I didn't get back to you on this. Automating the docs with Sphinx is the correct way of doing things but we've already using a free service called [Read The Docs](https://readthedocs.org/) to do this:

- http://pifacecommon.readthedocs.org/en/latest/
- http://pifacedigitalio.readthedocs.org/en/latest/

This is fast becoming the standard documentation platform for open source projects. It's searchable and follows a consistent (mobile accessible) theme.

**Comment by pedromorgan** [comment]
Hi Tom..

Am familiar with ReadTheDocs, doxygen, sphinx et all (was 50 last week, having started on a zxspectrum ;-)

The snag with readthedocs, is that it dont interlink docs, unless u can run the compile twice ..

So I'll get this site up and running tonite.. so i can see what i mean...  my target would be a subdomain eg docs.piface.org

**Comment by pedromorgan** [comment]
Check this other site for flightgear on doxygen for inspiration
http://api-docs.freeflightsim.org/
